import { useEffect, useState } from 'react';
import axios from 'axios';
import { useAppContext } from '../context/AppContext';
import { Navigate } from 'react-router-dom';
import { Lightbulb } from 'lucide-react';

export default function InsightPage() {
  const { sessionId } = useAppContext();
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (sessionId) {
      axios.get(`http://localhost:8000/api/insights/${sessionId}`)
        .then(res => {
          setInsights(res.data.insights || []);
          setLoading(false);
        })
        .catch(err => {
          console.error(err);
          setLoading(false);
        });
    }
  }, [sessionId]);

  if (!sessionId) return <Navigate to="/" />;

  if (loading) return (
    <div className="flex flex-col items-center justify-center h-full p-10 text-center">
      <Lightbulb className="w-16 h-16 text-amber-400 mb-4 animate-pulse" />
      <div className="text-xl font-bold text-slate-700">AI is analyzing your dataset...</div>
      <p className="text-slate-500 mt-2">Discovering hidden trends, anomalies, and patterns.</p>
    </div>
  );

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-black text-slate-900">AI Data Insights</h1>
        <p className="text-slate-500 mt-2">Top 5 findings generated by the Gemini Agent.</p>
      </div>

      <div className="space-y-6">
        {insights.map((insight, idx) => (
          <div key={idx} className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-start gap-4 hover:shadow-md transition-shadow border-l-4 border-l-amber-400">
            <div className="bg-amber-100 p-3 rounded-full text-amber-600">
              <Lightbulb className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-800 mb-1">Insight #{idx + 1}</h3>
              <p className="text-slate-600 leading-relaxed">{insight}</p>
            </div>
          </div>
        ))}
        {insights.length === 0 && (
          <div className="p-10 text-center text-slate-500 bg-white rounded-2xl border border-slate-200">
            No insights could be generated. Make sure your GEMINI_API_KEY is configured.
          </div>
        )}
      </div>
    </div>
  );
}
